### ISSUE TITLE
Can't removed facet in IE or Firefox

### ISSUE THREAD

**Issue by senyzspalding** [monixis/eaditorsearch#10]
The X to the right of the facet to deselect it is not clickable in Firefox or IE.

**Comment by senyzspalding** [comment]
It appears the issue is that in HTML 5 an A element cannot be in a button element.  I moved it so the button element was within the A element which works with removed the facet in regards to results but it still has the facet listed at the top. 

![image](https://user-images.githubusercontent.com/6430541/33847912-22e5edea-de7a-11e7-80ba-ab5b0c1ecebf.png)

**Comment by senyzspalding** [comment]
Adding a $( "a" ).remove( ".remove" );  to .on('click', '.remove', function() did the trick

**Comment by monixis** [comment]
Hi Zach,
Could you check in Chrome. Looks like it is giving problem there.

**Comment by senyzspalding** [comment]
It does work in Chrome, you might have caught me fiddling with it.  I ran into another issue it removes all the links that have a class of remove.  So if you have two or three facets it will remove all of them now, I was trying to figure out how to use the ID for the remove.

**Comment by monixis** [comment]
The <a> has to be unique for it to be removed. I think I got it on my end. Just made a commit.

**Comment by senyzspalding** [comment]
Thank You that took care of the issue.
