### ISSUE TITLE
Search Box doesn't work

### ISSUE THREAD

**Issue by senyzspalding** [monixis/eaditorsearch#19]
I just did a pull and something in the update brakes the search box.  I did roll back the change on the live site so the work would work again.  
The last working pull for the beta site was on March 6th

**Comment by monixis** [comment]
Zach, 
Could you check now? It should be working fine with the new clean urls.

**Comment by senyzspalding** [comment]
Git did the pull again and searching is not working in Firefox or Chome.  I am leaving it so you can see

**Comment by monixis** [comment]
Can you verify that 
1> config file has the ''http://beta.empireadc.org' without the last '/'  as the base url and
2> there exists a .htaccess file in the root directory of eaditorsearch.

**Comment by monixis** [comment]
Zach, 
In controller>eaditorsearch.php I forgot to remove line 38 code: echo $resultsLink; that will display the code for testing. 
Thanks,
Monish

**Comment by senyzspalding** [comment]
This issue has been resolved
