### ISSUE TITLE
Chronology design issue

### ISSUE THREAD

**Issue by monixis** [monixis/eaditorsearch#20]
Compare this chronology:  https://www.empireadc.org/ead/nsyu/id/martin_cj with this one: http://beta.empireadc.org/eaditorsearch/ead/nsyu/martin_cj

From Jen:
"Two issues with the Chronology display:
1. Date ranges don't display in the little blue circles. They are designed for a single year, but some chronologies will have date ranges.
2. If years are skipped in the chronology they shouldn't be included in the display. They are currently displaying with empty text bubbles."

**Comment by dheeraj-karnati** [comment]
1. Changed Blue circle shape into oval shape to show the hidden content. 
2. Fixed: In the old chronology, they misplaced the list of events belong to a particular period of time. 
 _example: the above exemplified EAD has list of events under chronitem 1922-1923. they are displaying under 1921-1922 in old application._

**Comment by monixis** [comment]
Thanks.
